// @generated by protoc-gen-es v2.13.0 with parameter "target=ts,import_extension=js"
// @generated from file kokoro/common/v1/projection_integrity.proto (package kokoro.common.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file kokoro/common/v1/projection_integrity.proto.
 */
export const file_kokoro_common_v1_projection_integrity: GenFile = /*@__PURE__*/
  fileDesc("Citrb2tvcm8vY29tbW9uL3YxL3Byb2plY3Rpb25faW50ZWdyaXR5LnByb3RvEhBrb2tvcm8uY29tbW9uLnYxIsgBChNQcm9qZWN0aW9uU2lnbmF0dXJlEk0KCWFsZ29yaXRobRgBIAEoDjIuLmtva29yby5jb21tb24udjEuUHJvamVjdGlvblNpZ25hdHVyZUFsZ29yaXRobUIKukgHggEEEAEgABJGCgxrZXlfcmV2aXNpb24YAiABKAlCMLpILXIrEAEYgAIyJF5bQS1aYS16MC05XVtBLVphLXowLTkuXzpALV17MCwyNTV9JBIaCglzaWduYXR1cmUYAyABKAxCB7pIBHoCaEAqegocUHJvamVjdGlvblNpZ25hdHVyZUFsZ29yaXRobRIuCipQUk9KRUNUSU9OX1NJR05BVFVSRV9BTEdPUklUSE1fVU5TUEVDSUZJRUQQABIqCiZQUk9KRUNUSU9OX1NJR05BVFVSRV9BTEdPUklUSE1fRUQyNTUxORABYgZwcm90bzM", [file_buf_validate_validate]);

/**
 * Publicly verifiable signature. key_revision selects an immutable published
 * Ed25519 public key; it is not a secret or a rotating delivery credential.
 *
 * @generated from message kokoro.common.v1.ProjectionSignature
 */
export type ProjectionSignature = Message<"kokoro.common.v1.ProjectionSignature"> & {
  /**
   * @generated from field: kokoro.common.v1.ProjectionSignatureAlgorithm algorithm = 1;
   */
  algorithm: ProjectionSignatureAlgorithm;

  /**
   * @generated from field: string key_revision = 2;
   */
  keyRevision: string;

  /**
   * @generated from field: bytes signature = 3;
   */
  signature: Uint8Array;
};

/**
 * Describes the message kokoro.common.v1.ProjectionSignature.
 * Use `create(ProjectionSignatureSchema)` to create a new message.
 */
export const ProjectionSignatureSchema: GenMessage<ProjectionSignature> = /*@__PURE__*/
  messageDesc(file_kokoro_common_v1_projection_integrity, 0);

/**
 * @generated from enum kokoro.common.v1.ProjectionSignatureAlgorithm
 */
export enum ProjectionSignatureAlgorithm {
  /**
   * @generated from enum value: PROJECTION_SIGNATURE_ALGORITHM_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: PROJECTION_SIGNATURE_ALGORITHM_ED25519 = 1;
   */
  ED25519 = 1,
}

/**
 * Describes the enum kokoro.common.v1.ProjectionSignatureAlgorithm.
 */
export const ProjectionSignatureAlgorithmSchema: GenEnum<ProjectionSignatureAlgorithm> = /*@__PURE__*/
  enumDesc(file_kokoro_common_v1_projection_integrity, 0);
