// @generated by contract/generate.mjs; DO NOT EDIT.
export const contractMetadata = Object.freeze({
  schemaId: "kokoro.platform.site.v1.SiteLifecycleService",
  schemaVersion: 1,
  sourceDigestSha256: "a4b4529974f0da13d9afdab6ab50c3e4cdbd4a9b01797d6fa6c7a8bf1ee14c1a",
  artifactDigestSha256: "e34a32e0ceebba140164090420fb0145a38159e20d9c4deb6f9a581c0e5d7bc2",
  sourcePaths: Object.freeze([
    "kokoro/common/v1/error.proto",
    "kokoro/common/v2/command_envelope.proto",
    "kokoro/platform/admin/v2/admin_shared.proto",
    "kokoro/platform/site/v1/site_lifecycle.proto",
  ]),
  generatorVersion: "2.13.0",
  runtimeVersion: "2.13.0",
});
