// @generated by contract/generate.mjs; DO NOT EDIT.
export const contractMetadata = Object.freeze({
  schemaId: "kokoro.platform.authorization.v1.SessionAuthorizationService",
  schemaVersion: 1,
  sourceDigestSha256: "24b0ff8d5f44b09518f4d83fef6ab7639b7869999f23eedb4b984733b4bf2bb7",
  artifactDigestSha256: "3fd2a81bb36d273eef8d0307746f7dc587fa8e384f9da9b24eaf3b87b1cd2889",
  sourcePaths: Object.freeze([
    "kokoro/platform/authorization/v1/session_authorization.proto",
  ]),
  generatorVersion: "2.13.0",
  runtimeVersion: "2.13.0",
});
