// @generated by contract/generate.mjs; DO NOT EDIT.
export const contractMetadata = Object.freeze({
  schemaId: "kokoro.platform.model.image.v1.ImageEffectV1Service",
  schemaVersion: 1,
  sourceDigestSha256: "61f19cd5436830b0866a2fc58028414ecade9823cab8395f2a9b348ff84cee2c",
  artifactDigestSha256: "53ee0c12a18decee45180600aa220ac29253c232848b976d38cd3696b019e055",
  sourcePaths: Object.freeze([
    "kokoro/common/v1/error.proto",
    "kokoro/common/v2/command_envelope.proto",
    "kokoro/platform/model/image/v1/image_effect.proto",
  ]),
  generatorVersion: "2.13.0",
  runtimeVersion: "2.13.0",
});
