// @generated by contract/generate.mjs; DO NOT EDIT.
export const contractMetadata = Object.freeze({
  schemaId: "kokoro.platform.product.v1.ProductCatalogPublicationService",
  schemaVersion: 1,
  sourceDigestSha256: "3aa1b627b4d65f5bbfd1146956844132ad304e3523b7c3ada7c4773bdc621360",
  artifactDigestSha256: "78fee49f342cfadf1fec836eadb16c569b59a3fabc7dbe72ba290e0d0a0d6cce",
  sourcePaths: Object.freeze([
    "kokoro/common/v1/error.proto",
    "kokoro/common/v2/command_envelope.proto",
    "kokoro/platform/admin/v2/admin_shared.proto",
    "kokoro/platform/publication/v1/publication_common.proto",
    "kokoro/platform/product/v1/product_catalog_publication.proto",
  ]),
  generatorVersion: "2.13.0",
  runtimeVersion: "2.13.0",
});
