export type MemoryDomainErrorCode =
  | "MEMORY_CATEGORY_INVALID"
  | "MEMORY_DIGEST_INVALID"
  | "MEMORY_ENTRY_INVALID"
  | "MEMORY_ENTRY_FENCE_CONFLICT"
  | "MEMORY_ENTRY_STATE_CONFLICT"
  | "MEMORY_FEATURE_POLICY_CONFLICT"
  | "MEMORY_INSTANT_INVALID"
  | "MEMORY_INT8_INVALID"
  | "MEMORY_LEARNING_STATE_CONFLICT"
  | "MEMORY_PROTECTED_CONTENT_INVALID"
  | "MEMORY_REFERENCE_INVALID"
  | "MEMORY_REVISION_CONFLICT"
  | "MEMORY_SCOPE_INVALID"
  | "MEMORY_SPACE_INVALID"
  | "MEMORY_SPACE_STATE_CONFLICT"
  | "MEMORY_USE_STATE_CONFLICT"
  | "MEMORY_VERSION_CONFLICT";

export class MemoryDomainError extends Error {
  readonly name = "MemoryDomainError";

  constructor(readonly code: MemoryDomainErrorCode) {
    super(code);
  }
}
