// @generated by contract/generate.mjs; DO NOT EDIT.
export const contractMetadata = Object.freeze({
  schemaId: "kokoro.platform.site.v1.SiteProvisioningService",
  schemaVersion: 1,
  sourceDigestSha256: "106e0f6b3a636211551fea3e1336663fa4e30105751f1badacafd61663907fe4",
  artifactDigestSha256: "401de2314f90cc857c05044330b9c8aec6ad02aae68aabc0f5343f1c040a03a0",
  sourcePaths: Object.freeze([
    "kokoro/common/v1/error.proto",
    "kokoro/common/v2/command_envelope.proto",
    "kokoro/platform/admin/v2/admin_shared.proto",
    "kokoro/platform/site/v1/site_provisioning.proto",
  ]),
  generatorVersion: "2.13.0",
  runtimeVersion: "2.13.0",
});
