// @generated by contract/generate.mjs; DO NOT EDIT.
export const contractMetadata = Object.freeze({
  schemaId: "kokoro.platform.site.v1.SiteProvisioningService",
  schemaVersion: 1,
  sourceDigestSha256: "6885768f968b553efb87da06eeb42e55a928388080ebe1cf0363ec3a4a7cc9fe",
  artifactDigestSha256: "0c6578ea770679f437d2f608649b3cb7806c062b3418eff8663cb260aa8bb654",
  sourcePaths: Object.freeze([
    "kokoro/common/v1/error.proto",
    "kokoro/common/v2/command_envelope.proto",
    "kokoro/platform/admin/v2/admin_shared.proto",
    "kokoro/platform/site/v1/site_provisioning.proto",
  ]),
  generatorVersion: "2.13.0",
  runtimeVersion: "2.13.0",
});
