// @generated by contract/generate.mjs; DO NOT EDIT.
export const contractMetadata = Object.freeze({
  schemaId: "kokoro.platform.site.v1.SiteEvidenceAdmissionService",
  schemaVersion: 1,
  sourceDigestSha256: "478afb0b1f6434baee8f53e9bce81882eac384856ded999523211fac669ed3c6",
  artifactDigestSha256: "de4178f3e44d29c3b5b53e6f9b55efdaf0a7219af6d4abcacc160fc124ced0d3",
  sourcePaths: Object.freeze([
    "kokoro/common/v1/error.proto",
    "kokoro/common/v2/command_envelope.proto",
    "kokoro/platform/admin/v2/admin_shared.proto",
    "kokoro/platform/publication/v1/publication_common.proto",
    "kokoro/platform/site/v1/site_publication.proto",
  ]),
  generatorVersion: "2.13.0",
  runtimeVersion: "2.13.0",
});
