// @generated by contract/generate.mjs; DO NOT EDIT.
export const contractMetadata = Object.freeze({
  schemaId: "kokoro.agent.execution.v1.AgentExecutionEvidenceService",
  schemaVersion: 1,
  sourceDigestSha256: "fd45e6793c8d881467812bc30f1d82f3b2d1961d583b630bcbefb284651461cb",
  artifactDigestSha256: "afa59f8b775083e7c47cf2bcff35530c303fee17d742991132b8ee1c298fd998",
  sourcePaths: Object.freeze([
    "kokoro/agent/execution/v1/agent_execution_evidence.proto",
  ]),
  generatorVersion: "2.13.0",
  runtimeVersion: "2.13.0",
});
