// @generated by contract/generate.mjs; DO NOT EDIT.
export const contractMetadata = Object.freeze({
  schemaId: "kokoro.agent.execution.v1.AgentExecutionEvidenceService",
  schemaVersion: 1,
  sourceDigestSha256: "274b0c623b56f21b1e5dcd841e9f77d574d3156a9a2b5b014710a68b31cc0922",
  artifactDigestSha256: "dd4f6c81ecc1e09d4131058d2b21c2bc7fe4e82b3ae771452fe28c68cb086166",
  sourcePaths: Object.freeze([
    "kokoro/agent/execution/v1/agent_execution_evidence.proto",
  ]),
  generatorVersion: "2.13.0",
  runtimeVersion: "2.13.0",
});
