// @generated by contract/generate.mjs; DO NOT EDIT.
export const contractMetadata = Object.freeze({
  schemaId: "kokoro.platform.credit.v1.AdminCreditService",
  schemaVersion: 1,
  sourceDigestSha256: "9348e430e1317c3252b1e3af34e37068d3a72bc2599a2c10a51a2162f311a90c",
  artifactDigestSha256: "82dc768060834944cdfe625cf920c85cdd506f1f33eb4b6561670da52ca29701",
  sourcePaths: Object.freeze([
    "kokoro/common/v2/command_envelope.proto",
    "kokoro/platform/admin/v2/admin_shared.proto",
    "kokoro/platform/credit/v1/admin_credit.proto",
  ]),
  generatorVersion: "2.13.0",
  runtimeVersion: "2.13.0",
});
