// @generated by contract/generate.mjs; DO NOT EDIT.
export const contractMetadata = Object.freeze({
  schemaId: "kokoro.platform.commerce.v1.AdminCommerceService",
  schemaVersion: 1,
  sourceDigestSha256: "9536fff15d9b81e5d4dd457dfc3fc833aecb0ddff60ecc077d06c6e6c259fefc",
  artifactDigestSha256: "436f0e66c7198824fbf47c5651e6fc0c3dd6ac2fac8bdcb57f7750ddd8cb3690",
  sourcePaths: Object.freeze([
    "kokoro/common/v1/error.proto",
    "kokoro/common/v2/command_envelope.proto",
    "kokoro/platform/admin/v2/admin_shared.proto",
    "kokoro/platform/commerce/v1/admin_commerce.proto",
  ]),
  generatorVersion: "2.13.0",
  runtimeVersion: "2.13.0",
});
