// @generated by contract/generate.mjs; DO NOT EDIT.
export const contractMetadata = Object.freeze({
  schemaId: "kokoro.platform.commerce.v1.AdminCommerceService",
  schemaVersion: 1,
  sourceDigestSha256: "5fa65ab08d462af8c8d1f48f3dfa21740a9786da1279e19c5a6df2bb09d96cc8",
  artifactDigestSha256: "8ace92995c2bbf16053641f2d9332f355f5a2186fbe9fc43713f639032d69a04",
  sourcePaths: Object.freeze([
    "kokoro/common/v1/error.proto",
    "kokoro/common/v2/command_envelope.proto",
    "kokoro/platform/admin/v2/admin_shared.proto",
    "kokoro/platform/commerce/v1/admin_commerce.proto",
  ]),
  generatorVersion: "2.13.0",
  runtimeVersion: "2.13.0",
});
