export const ADMIN_UNAUTHENTICATED_ERROR_CODES = Object.freeze([
  "ADMIN_SESSION_UNAUTHENTICATED",
  "ADMIN_SESSION_INVALID",
  "ADMIN_SESSION_AUTHORITY_MISMATCH",
  "ADMIN_SESSION_SECURITY_EPOCH_STALE",
  "ADMIN_OPERATOR_AUTHORITY_INVALID",
  "ADMIN_OPERATOR_ATTESTATION_MISMATCH",
  "ADMIN_VERIFIED_PEER_REQUIRED",
  "ADMIN_SESSION_CREDENTIAL_REQUIRED",
  "ADMIN_SESSION_CREDENTIAL_INVALID",
] as const);

export const ADMIN_PERMISSION_DENIED_ERROR_CODES = Object.freeze([
  "ADMIN_PERMISSION_DENIED",
  "ADMIN_SCOPE_DEPLOYMENT_MISMATCH",
  "ADMIN_STEP_UP_REQUIRED",
  "ADMIN_SELF_ESCALATION_DENIED",
  "ADMIN_SITE_SCOPE_INVALID",
  "ADMIN_SITE_SCOPE_DENIED",
  "ADMIN_GLOBAL_SCOPE_INVALID",
  "ADMIN_GLOBAL_SCOPE_DENIED",
  "ADMIN_BREAKGLASS_SCOPE_INVALID",
  "ADMIN_BREAKGLASS_SCOPE_DENIED",
  "ADMIN_BREAKGLASS_TARGET_DENIED",
  "ADMIN_WORKLOAD_AXIS_MISMATCH",
] as const);

export const ADMIN_REQUEST_INVALID_ERROR_CODES = Object.freeze([
  "ADMIN_STEP_UP_TARGET_REQUIRED",
  "ADMIN_SCOPE_REQUIRED",
  "ADMIN_BREAKGLASS_EXPIRY_REQUIRED",
  "ADMIN_REQUEST_ID_INVALID",
] as const);

export const MODEL_CONTROL_CONTRACTED_INVALID_CODES = Object.freeze([
  "ADMIN_PAGE_TOKEN_INVALID",
  "MODEL_ADMIN_PAGE_TOKEN_INVALID",
] as const);

export const MODEL_CONTROL_REQUEST_INVALID_CODES = Object.freeze([
  "MODEL_ADMIN_PAGE_SIZE_INVALID",
  "MODEL_CONTROL_CONTEXT_REQUIRED",
  "MODEL_CONTROL_QUERY_CONTEXT_REQUIRED",
  "MODEL_CONTROL_COMMAND_IDENTITY_REQUIRED",
  "MODEL_CONTROL_COMMAND_DIGEST_ALGORITHM_INVALID",
  "MODEL_CONTROL_COMMAND_DIGEST_INVALID",
  "MODEL_CONTROL_SCOPE_KIND_INVALID",
  "MODEL_INVENTORY_IMPORT_EFFECT_REQUIRED",
  "MODEL_INVENTORY_REQUIRED",
  "MODEL_INVENTORY_ACTIVATION_EFFECT_REQUIRED",
  "MODEL_SITE_POLICY_EFFECT_REQUIRED",
  "MODEL_OPTION_MATERIALIZATION_EFFECT_REQUIRED",
  "MODEL_OPTION_ORCHESTRATION_REQUIRED",
  "MODEL_OPTION_GENERATION_REQUIRED",
  "MODEL_SITE_RELEASE_CATALOG_EFFECT_REQUIRED",
  "MODEL_PRODUCT_INVALID",
  "MODEL_ROUTE_ROLE_INVALID",
  "MODEL_PROVIDER_ADAPTER_INVALID",
  "MODEL_PROVIDER_STATUS_INVALID",
  "MODEL_PROVIDER_HEALTH_INVALID",
  "MODEL_PROVIDER_OBSERVED_AT_INVALID",
  "MODEL_SITE_CATALOG_MODE_INVALID",
  "MODEL_SITE_ASSIGNMENT_MODE_INVALID",
  "MODEL_OPTION_LIFECYCLE_INVALID",
  "MODEL_SITE_ACTIVE_CATALOG_DIGEST_FORBIDDEN",
  "MODEL_SITE_PINNED_CATALOG_DIGEST_REQUIRED",
] as const);

export const MODEL_CONTROL_INTERNAL_INVARIANT_CODES = Object.freeze([
  "ADMIN_AUTHORIZATION_TIME_INVALID",
  "MODEL_ADMIN_TIME_INVALID",
  "MODEL_ADMIN_PRODUCT_INVALID",
  "MODEL_INVENTORY_ACTIVATED_REVISION_INVALID",
  "MODEL_SITE_POLICY_REVISION_INVALID",
  "MODEL_SITE_RELEASE_CATALOG_TIME_INVALID",
  "MODEL_CONTROL_RECEIPT_TIME_INVALID",
  "MODEL_SELECTION_DECISION_NOT_PERSISTED",
] as const);

export type ModelControlErrorClassification =
  | "adminSessionUnauthenticated"
  | "adminPermissionDenied"
  | "invalidRequest"
  | "internal";

export function classifyModelControlError(error: unknown): ModelControlErrorClassification {
  const code = error instanceof Error ? error.message : "";
  if (contains(ADMIN_UNAUTHENTICATED_ERROR_CODES, code)) return "adminSessionUnauthenticated";
  if (contains(ADMIN_PERMISSION_DENIED_ERROR_CODES, code)) return "adminPermissionDenied";
  if (contains(ADMIN_REQUEST_INVALID_ERROR_CODES, code) ||
      contains(MODEL_CONTROL_REQUEST_INVALID_CODES, code)) return "invalidRequest";
  return "internal";
}

function contains(values: readonly string[], value: string): boolean {
  return values.includes(value);
}
