import {
  ADMIN_PERMISSION_DENIED_ERROR_CODES,
  ADMIN_REQUEST_INVALID_ERROR_CODES,
  ADMIN_STEP_UP_REQUIRED_ERROR_CODES,
  ADMIN_UNAUTHENTICATED_ERROR_CODES,
  classifyAdminConnectError,
} from "../../../admin/interfaces/connect/admin-connect-error-policy.js";

export {
  ADMIN_PERMISSION_DENIED_ERROR_CODES,
  ADMIN_REQUEST_INVALID_ERROR_CODES,
  ADMIN_STEP_UP_REQUIRED_ERROR_CODES,
  ADMIN_UNAUTHENTICATED_ERROR_CODES,
};

export const MODEL_CONTROL_CONTRACTED_INVALID_CODES = Object.freeze([
  "ADMIN_PAGE_TOKEN_INVALID",
  "MODEL_ADMIN_PAGE_TOKEN_INVALID",
] as const);

export const MODEL_CONTROL_REQUEST_INVALID_CODES = Object.freeze([
  "MODEL_ADMIN_PAGE_SIZE_INVALID",
  "MODEL_CONTROL_CONTEXT_REQUIRED",
  "MODEL_CONTROL_QUERY_CONTEXT_REQUIRED",
  "MODEL_CONTROL_COMMAND_IDENTITY_REQUIRED",
  "MODEL_CONTROL_COMMAND_ID_INVALID",
  "MODEL_CONTROL_REQUEST_DIGEST_INVALID",
  "MODEL_CONTROL_COMMAND_DIGEST_ALGORITHM_INVALID",
  "MODEL_CONTROL_COMMAND_DIGEST_INVALID",
  "MODEL_CONTROL_SCOPE_KIND_INVALID",
  "MODEL_CONTROL_RECEIPT_SCOPE_INVALID",
  "MODEL_CONTROL_RECEIPT_OPERATION_INVALID",
  "MODEL_CONTROL_RECEIPT_DIGEST_ALGORITHM_INVALID",
  "COMMAND_ID_INVALID",
  "MODEL_INVENTORY_IMPORT_EFFECT_REQUIRED",
  "MODEL_INVENTORY_REQUIRED",
  "MODEL_INVENTORY_ACTIVATION_EFFECT_REQUIRED",
  "MODEL_SITE_POLICY_EFFECT_REQUIRED",
  "MODEL_OPTION_MATERIALIZATION_EFFECT_REQUIRED",
  "MODEL_OPTION_ORCHESTRATION_REQUIRED",
  "MODEL_OPTION_GENERATION_REQUIRED",
  "MODEL_SITE_RELEASE_CATALOG_EFFECT_REQUIRED",
  "MODEL_PRODUCT_INVALID",
  "MODEL_ROUTE_ROLE_INVALID",
  "MODEL_PROVIDER_ADAPTER_INVALID",
  "MODEL_PROVIDER_STATUS_INVALID",
  "MODEL_PROVIDER_HEALTH_INVALID",
  "MODEL_PROVIDER_OBSERVED_AT_INVALID",
  "MODEL_PROVIDER_AVAILABILITY_EPOCH_INVALID",
  "MODEL_CONTEXT_WINDOW_INVALID",
  "MODEL_INVENTORY_EXPECTED_POINTER_REVISION_INVALID",
  "MODEL_SITE_POLICY_EXPECTED_REVISION_INVALID",
  "MODEL_SITE_CATALOG_MODE_INVALID",
  "MODEL_SITE_ASSIGNMENT_MODE_INVALID",
  "MODEL_OPTION_LIFECYCLE_INVALID",
  "MODEL_SITE_ACTIVE_CATALOG_DIGEST_FORBIDDEN",
  "MODEL_SITE_PINNED_CATALOG_DIGEST_REQUIRED",
] as const);

export const MODEL_CONTROL_INTERNAL_INVARIANT_CODES = Object.freeze([
  "ADMIN_AUTHORIZATION_TIME_INVALID",
  "MODEL_ADMIN_TIME_INVALID",
  "MODEL_ADMIN_PRODUCT_INVALID",
  "MODEL_INVENTORY_ACTIVATED_REVISION_INVALID",
  "MODEL_SITE_POLICY_REVISION_INVALID",
  "MODEL_SITE_RELEASE_CATALOG_TIME_INVALID",
  "MODEL_CONTROL_RECEIPT_TIME_INVALID",
  "MODEL_CONTROL_RECEIPT_INVALID",
  "MODEL_CONTROL_RECEIPT_RESULT_INVALID",
  "MODEL_CONTROL_RECEIPT_READER_REQUIRED",
  "MODEL_SELECTION_DECISION_NOT_PERSISTED",
] as const);

export type ModelControlErrorClassification =
  | "adminSessionUnauthenticated"
  | "adminPermissionDenied"
  | "adminStepUpRequired"
  | "invalidRequest"
  | "internal";

export function classifyModelControlError(error: unknown): ModelControlErrorClassification {
  const code = error instanceof Error ? error.message : "";
  const admin = classifyAdminConnectError(error);
  if (admin === "unauthenticated") return "adminSessionUnauthenticated";
  if (admin === "permissionDenied") return "adminPermissionDenied";
  if (admin === "stepUpRequired") return "adminStepUpRequired";
  if (admin === "invalidRequest" ||
      contains(MODEL_CONTROL_REQUEST_INVALID_CODES, code)) return "invalidRequest";
  return "internal";
}

function contains(values: readonly string[], value: string): boolean {
  return values.includes(value);
}
