// @generated by contract/generate.mjs; DO NOT EDIT.
export const contractMetadata = Object.freeze({
  schemaId: "kokoro.platform.model.v1.ModelControlService",
  schemaVersion: 1,
  sourceDigestSha256: "105aabeb4710adc9cab35f3aa065b6c6ceeef9845b572b40400877ec0ce0e0db",
  artifactDigestSha256: "8e40edf09c8575130d862c4718dc8482f9e8246f4e20a51f2777197cd3a2862c",
  sourcePaths: Object.freeze([
    "kokoro/common/v1/error.proto",
    "kokoro/common/v2/command_envelope.proto",
    "kokoro/platform/admin/v2/admin_shared.proto",
    "kokoro/platform/model/v1/model_control.proto",
  ]),
  generatorVersion: "2.13.0",
  runtimeVersion: "2.13.0",
});
