export type MediaChildInvalidStateCode =
  | "CREDIT_CHILD_ALLOCATION_CAPACITY_EXCEEDED"
  | "CREDIT_CHILD_ALREADY_TERMINAL"
  | "CREDIT_CHILD_CAPTURED_AMOUNT_INVALID"
  | "CREDIT_CHILD_CEILING_INVALID"
  | "CREDIT_CHILD_COMMAND_INVALID"
  | "CREDIT_CHILD_COMMITTED_STOCK_PENDING"
  | "CREDIT_CHILD_DESCENDANT_PENDING"
  | "CREDIT_CHILD_EPOCH_STALE"
  | "CREDIT_CHILD_EXPIRY_INVALID"
  | "CREDIT_CHILD_FENCE_EXHAUSTED"
  | "CREDIT_CHILD_NOT_RETURNABLE"
  | "CREDIT_CHILD_OWNER_EVIDENCE_INVALID"
  | "CREDIT_CHILD_OWNER_EVIDENCE_MISMATCH"
  | "CREDIT_CHILD_PARENT_EPOCH_STALE"
  | "CREDIT_CHILD_PARENT_FENCE_INVALID"
  | "CREDIT_CHILD_PARENT_NOT_ACTIVE"
  | "CREDIT_CHILD_PARENT_NOT_RETURNABLE"
  | "CREDIT_CHILD_PARENT_NOT_ROOT"
  | "CREDIT_CHILD_PARENT_REVISION_STALE"
  | "CREDIT_CHILD_PARENT_STOCK_INVALID"
  | "CREDIT_CHILD_PARTIAL_RETURN_INVALID"
  | "CREDIT_CHILD_PURPOSE_INVALID"
  | "CREDIT_CHILD_RECEIPT_DIGEST_INVALID"
  | "CREDIT_CHILD_RECONCILIATION_REQUIRED"
  | "CREDIT_CHILD_RESERVED_SEGMENT_STOCK_INVALID"
  | "CREDIT_CHILD_RETURN_FENCE_INVALID"
  | "CREDIT_CHILD_REVISION_STALE"
  | "CREDIT_CHILD_ROOT_NOT_OPEN"
  | "CREDIT_CHILD_ROOT_NOT_RETURNABLE"
  | "CREDIT_CONSUMPTION_SCOPE_INVALID"
  | "CREDIT_INSTANT_INVALID"
  | "CREDIT_OPERATION_RECEIPT_SCOPE_MISMATCH"
  | "CREDIT_REFERENCE_INVALID"
  | "CREDIT_REQUEST_DIGEST_INVALID"
  | "CREDIT_UUID_REFERENCE_INVALID";

export type CreditDomainErrorCode = MediaChildInvalidStateCode
  | "CREDIT_ALLOCATION_CONSERVATION_VIOLATION"
  | "CREDIT_ALLOCATION_REVISION_INVALID"
  | "CREDIT_CHILD_TERMINAL_REVISION_INVALID"
  | "CREDIT_GRANT_AVAILABILITY_INVALID"
  | "CREDIT_GRANT_ID_INVALID"
  | "CREDIT_INSUFFICIENT_AVAILABLE"
  | "CREDIT_RESERVATION_AMOUNT_INVALID"
  | "CREDIT_SEGMENT_ALLOCATION_EPOCH_STALE"
  | "CREDIT_SEGMENT_ALLOCATION_REVISION_STALE"
  | "CREDIT_SEGMENT_CAPACITY_EXCEEDED"
  | "CREDIT_SEGMENT_NOT_COMMITTABLE"
  | "CREDIT_SEGMENT_NOT_RATABLE"
  | "CREDIT_SEGMENT_NOT_RECONCILABLE"
  | "CREDIT_SEGMENT_NOT_RELEASABLE"
  | "CREDIT_SEGMENT_NOT_SETTLEABLE"
  | "CREDIT_SEGMENT_RECONCILIATION_EVIDENCE_INVALID"
  | "CREDIT_SEGMENT_RELEASE_EVIDENCE_INVALID"
  | "CREDIT_SEGMENT_VERSION_INVALID"
  | "CREDIT_SETTLEMENT_AMOUNT_EXCEEDS_SEGMENT"
  | "CREDIT_SETTLEMENT_COMMITTED_STOCK_INVALID"
  | "CREDIT_SETTLEMENT_CORRECTION_ALLOCATION_NOT_OPEN"
  | "CREDIT_SETTLEMENT_CORRECTION_CAPACITY_INVALID"
  | "CREDIT_SETTLEMENT_REFERENCE_INVALID"
  | "CREDIT_USAGE_CLOSURE_REFERENCE_INVALID";

export class CreditDomainError<Code extends CreditDomainErrorCode = CreditDomainErrorCode> extends Error {
  readonly code: Code;

  constructor(code: Code) {
    super(code);
    this.name = "CreditDomainError";
    this.code = code;
  }
}
