CREATE ROLE platform_migrator
  LOGIN NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS
  PASSWORD 'platform-migrator-ci';
CREATE ROLE platform_api
  LOGIN NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS
  PASSWORD 'platform-api-ci';
CREATE ROLE platform_admission
  LOGIN NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS
  PASSWORD 'platform-admission-ci';
CREATE ROLE platform_authorization
  LOGIN NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS
  PASSWORD 'platform-authorization-ci';
CREATE ROLE platform_asset_data_plane
  LOGIN NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS
  PASSWORD 'platform-asset-data-plane-ci';
CREATE ROLE platform_worker
  LOGIN NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS
  PASSWORD 'platform-worker-ci';
CREATE ROLE platform_admin
  LOGIN NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS
  PASSWORD 'platform-admin-ci';
CREATE ROLE platform_model_gateway
  LOGIN NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS
  PASSWORD 'platform-model-gateway-ci';

CREATE DATABASE kokoro_test_platform OWNER platform_migrator;
REVOKE ALL ON DATABASE kokoro_test_platform FROM PUBLIC;
GRANT CONNECT ON DATABASE kokoro_test_platform TO
  platform_migrator,
  platform_api,
  platform_admission,
  platform_authorization,
  platform_asset_data_plane,
  platform_worker,
  platform_admin,
  platform_model_gateway;
