export const hubPlatformModule = {
  id: "hub",
  labelKey: "platform.modules.hub",
  packageName: "@kokoro/hub",
  directory: "kokoro-hub",
  status: "active",
  kind: "capability-hub",
  envFile: "kokoro-hub/.env.example",
  storage: {
    primary: "mongo",
    ownsMigrations: false,
  },
  admin: {
    mode: "manifest",
    basePath: "/hub/admin",
    manifestExport: "hubAdminManifest",
  },
  runtime: {
    surfaces: ["http", "connectrpc", "admin-manifest"],
    routes: [
      "GET /healthz",
      // self 面（web-bff：信封 scope + user 成员校验）；MCP mutation 受部署门 KOKORO_HUB_MCP_MUTATION 控（off 恒 503）。
      "GET /hub/self/skills/pool",
      "GET /hub/self/skills/quota",
      "GET /hub/self/skills/:name/revisions",
      "POST /hub/self/skills/:name/enable",
      "POST /hub/self/skills/:name/disable",
      "POST /hub/self/skills/upload/preview",
      "POST /hub/self/skills/upload/confirm",
      "GET /hub/self/mcp/servers",
      "POST /hub/self/mcp/servers (gated: KOKORO_HUB_MCP_MUTATION)",
      "POST /hub/self/mcp/servers/:name/enable (gated: KOKORO_HUB_MCP_MUTATION)",
      "POST /hub/self/mcp/servers/:name/disable (gated: KOKORO_HUB_MCP_MUTATION)",
      "DELETE /hub/self/mcp/servers/:name (gated: KOKORO_HUB_MCP_MUTATION)",
      "POST /hub/self/mcp/secrets",
      "GET /hub/self/mcp/secrets",
      "DELETE /hub/self/mcp/secrets/:handle",
      // admin 面（admin 网关）：manifest/审核/运营/官方位/软删/上传/MCP 管理。
      "GET /hub/admin/manifest",
      "GET /hub/admin/skills/pool",
      "GET /hub/admin/skills/quota",
      "POST /hub/admin/skills/:scope/:name/enable",
      "POST /hub/admin/skills/:scope/:name/disable",
      "POST /hub/admin/skills/:name/official-flags",
      "DELETE /hub/admin/skills/:scope/:name",
      "POST /hub/admin/skills/:scope/:name/curation",
      "POST /hub/admin/skills/:scope/:name/review",
      "POST /hub/admin/skills/upload/preview",
      "POST /hub/admin/skills/upload/confirm",
      "GET /hub/admin/skills/:scope/:name/revisions",
      "POST /hub/admin/mcp/servers",
      "GET /hub/admin/mcp/servers",
      "POST /hub/admin/mcp/servers/:scope/:name/enable",
      "POST /hub/admin/mcp/servers/:scope/:name/disable",
      "DELETE /hub/admin/mcp/servers/:scope/:name",
    ],
    notes: [
      "HTTP 权限面仅保留 /hub/self(web-bff 信封 self-service，成员校验+MCP mutation fail-closed) 与 /hub/admin(admin 网关管理面)。",
      "hub 是 skill/MCP 能力中台的管理写面权威（启停/官方位/软删/配额/池查询）。",
      "agent 只通过 mTLS ConnectRPC ResolveExecutionAssembly/FetchSkillArtifact 消费精确冻结的能力装配；不得直连 Hub Mongo 或对象存储。",
    ],
  },
  service: {
    serviceName: "kokoro-hub",
    portEnv: "KOKORO_HUB_PORT",
    defaultPort: 4251,
    baseUrlEnv: "KOKORO_HUB_BASE_URL",
  },
  dependencies: [],
  boundaries: {
    owns: [
      "skill registry write surface",
      "skill upload write surface (preview/confirm, content-addressed package publish)",
      "skill revision history (append-only)",
      "per-user skill enable/disable state",
      "skill official flags",
      "skill curation fields (display_weight/pinned/category, pool ordering)",
      "skill review status machine (pending/approved/rejected; V1 auto-approve on publish)",
      "namespace upload quota view and enforcement",
      "mcp server registry (register/pool/enable/disable/soft delete; secret refs only, no plaintext credentials)",
      "mcp secret broker (envelope AES-256-GCM at rest; opaque handle in/out; ResolveExecutionAssembly is the sole plaintext egress; per-namespace isolation)",
    ],
    doesNotOwn: [
      "skill assembly hot path (kokoro-agent)",
      "user identity",
      "namespace resolution",
    ],
  },
} as const;
