// @generated by contract/generate.mjs; DO NOT EDIT.
export const contractMetadata = Object.freeze({
  schemaId: "kokoro.session.admission.v1.SessionAdmissionOwnerService",
  schemaVersion: 1,
  sourceDigestSha256: "f6d4ac91096640eebc290c483f32e41d40618e8b3bd4daad923a4a7fb4b37759",
  artifactDigestSha256: "d2ac99a9093e5ea56e26cef7065d62d89339d52b61ae1e3e450d37afa95862d4",
  sourcePaths: Object.freeze([
    "kokoro/session/admission/v1/session_admission_owner.proto",
  ]),
  generatorVersion: "2.13.0",
  runtimeVersion: "2.13.0",
});
