// @generated by contract/generate.mjs; DO NOT EDIT.
export const contractMetadata = Object.freeze({
  schemaId: "kokoro.session.admission.v1.SessionAdmissionOwnerService",
  schemaVersion: 1,
  sourceDigestSha256: "a6d742d67e43e3336ad8aa87cd7e06c7c57a5f6ee99c8a7e7805cd52dc2150f4",
  artifactDigestSha256: "f284a43a9311cd1efe5ee182d5b352b5ea06b552887af7e19da5f43c91c7da84",
  sourcePaths: Object.freeze([
    "kokoro/session/admission/v1/session_admission_owner.proto",
  ]),
  generatorVersion: "2.13.0",
  runtimeVersion: "2.13.0",
});
