// @generated by contract/generate.mjs; DO NOT EDIT.
export const contractMetadata = Object.freeze({
  schemaId: "kokoro.platform.admin.v2.AdminQueryService",
  schemaVersion: 2,
  sourceDigestSha256: "6760ae5fdafa15ab3dd2648e9f0e329d560ee285d1843d41039b046eceae92fb",
  artifactDigestSha256: "d09706320fdd864d6baeccf19916a6a284e512e56a060a9fd6038db1e12f440e",
  sourcePaths: Object.freeze([
    "kokoro/common/v1/error.proto",
    "kokoro/common/v2/command_envelope.proto",
    "kokoro/platform/admin/v2/admin_shared.proto",
    "kokoro/platform/admin/v2/admin_query.proto",
  ]),
  generatorVersion: "2.13.0",
  runtimeVersion: "2.13.0",
});
