// @generated by contract/generate.mjs; DO NOT EDIT.
export const contractMetadata = Object.freeze({
  schemaId: "kokoro.platform.asset.v1.AssetEligibilityService",
  schemaVersion: 1,
  sourceDigestSha256: "386499afe96326251cd80325b56f5bea946e7b8766e520ad5b203553afd9ac8b",
  artifactDigestSha256: "2cf5d1ebe22393d08e9aab0282e8b16179fd00b8577e4340b901460f29a0b650",
  sourcePaths: Object.freeze([
    "kokoro/platform/asset/v1/asset_eligibility.proto",
  ]),
  generatorVersion: "2.13.0",
  runtimeVersion: "2.13.0",
});
