// @generated by contract/generate.mjs; DO NOT EDIT.
export const contractMetadata = Object.freeze({
  schemaId: "kokoro.session.media.v1.SessionMediaProjectionService",
  schemaVersion: 1,
  sourceDigestSha256: "2cde7e8813dc9dddfab79ba1f5d1dc9d43864beb595a47c6b40ef26b38f27a13",
  artifactDigestSha256: "761514ea2005acc25d1d8f44105be2328f4419f528ae96b28671bd74f895371c",
  sourcePaths: Object.freeze([
    "kokoro/platform/credit/v1/cost_projection.proto",
    "kokoro/platform/media/v1/media_projection.proto",
    "kokoro/session/media/v1/media_projection.proto",
  ]),
  generatorVersion: "2.13.0",
  runtimeVersion: "2.13.0",
});
