// @generated by contract/generate.mjs; DO NOT EDIT.
export const contractMetadata = Object.freeze({
  schemaId: "kokoro.platform.media.v1.MediaRuntimeService",
  schemaVersion: 1,
  sourceDigestSha256: "60bb452d039d5b8a106e311de9aad864826d5eb98c0ddf01c543b5adb9086650",
  artifactDigestSha256: "41413c8d9879972e59fbf206d0fb9465a388e0a112e7c6fe842ddd01f76a0597",
  sourcePaths: Object.freeze([
    "kokoro/platform/media/v1/media_runtime.proto",
  ]),
  generatorVersion: "2.13.0",
  runtimeVersion: "2.13.0",
});
