// @generated by contract/generate.mjs; DO NOT EDIT.
export const contractMetadata = Object.freeze({
  schemaId: "kokoro.platform.model.v1.ModelGatewayService",
  schemaVersion: 1,
  sourceDigestSha256: "6bd7b9223c96d180bbb33124485dc9cc9df1eeb9de33fe6a08adf2cfc31a52a5",
  artifactDigestSha256: "9f7f50554bfee64ed975e06d64e7fa5527387a395006094c4a04d79e229d3422",
  sourcePaths: Object.freeze([
    "kokoro/platform/model/v1/model_gateway.proto",
  ]),
  generatorVersion: "2.13.0",
  runtimeVersion: "2.13.0",
});
