// @generated by contract/generate.mjs; DO NOT EDIT.
export const contractMetadata = Object.freeze({
  schemaId: "kokoro.platform.model.v1.ModelGatewayService",
  schemaVersion: 1,
  sourceDigestSha256: "40cc0fc4c08f0d9a3d14b49540afd974674e91ecd6090f9dc8094d0a671bb5eb",
  artifactDigestSha256: "050363de11765964297682d8cfd5fc70670456c1b6c246f52238ef990dd17de3",
  sourcePaths: Object.freeze([
    "kokoro/platform/model/v1/model_gateway.proto",
  ]),
  generatorVersion: "2.13.0",
  runtimeVersion: "2.13.0",
});
