export type MemoryApplicationErrorCode =
  | "MEMORY_AUTHORIZATION_DENIED"
  | "MEMORY_AUTHORIZATION_FACTS_STALE"
  | "MEMORY_COMMAND_DIGEST_CONFLICT"
  | "MEMORY_ENTRY_NOT_FOUND"
  | "MEMORY_CONTENT_POLICY_REJECTED"
  | "MEMORY_OWNER_SNAPSHOT_STALE"
  | "MEMORY_PAGE_CURSOR_INVALID"
  | "MEMORY_PUBLIC_NOT_AVAILABLE"
  | "MEMORY_PUBLIC_NOT_RESTORABLE"
  | "MEMORY_PUBLIC_INPUT_INVALID"
  | "MEMORY_PUBLIC_SCOPE_UNAVAILABLE"
  | "MEMORY_PUBLIC_VERSION_CONFLICT"
  | "MEMORY_PARENT_SCOPE_INVALID"
  | "MEMORY_PERSISTENCE_CONFLICT"
  | "MEMORY_RECEIPT_INVALID"
  | "MEMORY_SPACE_NOT_FOUND";

export class MemoryApplicationError extends Error {
  readonly name = "MemoryApplicationError";

  constructor(readonly code: MemoryApplicationErrorCode) {
    super(code);
  }
}
